name: Forward
version: @version@
main: org.meowcat.minecraft.forward.Forward
api-version: 1.16
commands:
  forward:
    description: "A message forward plugin"
    aliases: [f, fd]
    permission: forward.use
    permission-message: "YOU HAVE NO PERMISSION!"