name: Forward
version: @version@
main: org.meowcat.minecraft.forward.Forward
api-version: 1.16
authors: [Itsusinn]
commands:
  forward:
    description: "A message forward plugin"
    aliases: [f,fd]
    permission: forward.use
    permission-message: "YOU HAVE NO PERMISSION!"
permissions:
  forward.use:
    description: "Permission to use forward plugins"
    default: op