name: Forward
version: 0.0.2
main: org.meowcat.minecraft.forward.Forward
author: Itsusinn
commands:
  forward:
    description: "A message forward plugin"
    aliases: [f,fd]
    permission: forward.use
    permission-message: "YOU HAVE NO PERMISSION!"
permissions:
  forward.use:
    description: "Permission to use forward plugins"
    default: op