name: EasyForward
version: 0.0.3
main: io.github.itsusinn.forward.bukkit.EasyForwardPlugin
author: Itsusinn
commands:
  forward:
    description: "A message forward plugin"
    aliases: [f,fd]
    permission: forward.use
    permission-message: "YOU HAVE NO PERMISSION!"
permissions:
  forward.use:
    description: "Permission to use forward plugin"
    default: op